services:
  notion-backup:
    container_name: notion-backup
    build: .
    environment:
      - FILTER=Test
      - NOTION_API_KEY=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
      - OUTPUT_DIR=/app/output
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    restart: unless-stopped
