services:
  notion-backup:
    container_name: notion-backup
    build: .
    environment:
      - FILTER=<FILTER>
      - BACKUP_INTERVAL=<BACKUP_INTERVAL>
      - NOTION_API_KEY=<NOTION_API_KEY>
      - OUTPUT_DIR=/app/output
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    restart: unless-stopped
